python Main.py \
    --dataset='gowalla' \
    --mask_epoch=300   `#300 is an example; increase it for better recommendation performance` \
    --lr=0.001 \
    --run_no_adj_weights True \
    --fix_epoch 3\
    --reg=1e-8 \
    --latdim=64 \
    --gnn_layer=2 \
    --adj_aug=True \
    --adj_aug_layer=1  `# Necessary for obtaining the final student`  \
    --use_adj_mask_aug=True `# Necessary for obtaining the final student` \
    --use_SM_edgeW2aug=True  `# Necessary for obtaining the final student` \
    --adj_mask_aug1=0.05 \
    --adj_mask_aug2=1.0 \
    --use_mTea2drop_edges=True \
    --use_tea2drop_edges=False  \
    --PRUNING_START=1 \
    --PRUNING_END=13 \
    --model_save_path=./outModels/gowalla/example1/checkpoints/ckpts \
    --his_save_path=./outModels/gowalla/example1/history/his \
    --middle_teacher_model=./inModels/gowalla/intermediate_KD_model_layer2_dim64_gowalla.mod \
    --distill_from_middle_model=True \
    --distill_from_teacher_model=False \
    --train_middle_model=False \
    --pruning_percent_adj=0.15 \
    --pruning_percent_emb=0.02 | tee ./logs/student_gowalla_example1_log
